// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float resolution;


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float _x = id.x/ resolution;
    float _y = id.y/ resolution;

    Result[id.xy] = float4(_x,_y,0,1);
}
